# Exported from Render on 2026-09-21T16:41:40Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: CloudCompiutingEx2
      runtime: python
      repo: https://github.com/THeyix/CloudCompiutingEx2
      plan: free
      region: frankfurt
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn your_application.wsgi
      autoDeployTrigger: commit
